apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-conf
  namespace: {{ template "web.namespace" . }}
data:
  nginx.conf: |-
      server {
          listen       8000;
          server_name  localhost;
          location / {
            root   /homework;
            index  index.html index.htm;
        }
      }
