apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}
  namespace: {{ template "web.namespace" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  selector:
    app: homework-app
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
