apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-status
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      name: nginx-status
      labels:
        app: nginx-status
    spec:
      containers:
      - name: nginx-status
        image: batkovyu/otus_nginx:0.1
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8080
      - name: nginx-prometheus-exporter
        args:
          - "--nginx.scrape-uri=http://localhost:8080/metrics"
        image: nginx/nginx-prometheus-exporter:latest
        ports:
          - name: metrics
            containerPort: 9113
      nodeSelector:
        homework: "true"