apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  containers:
  - name: web
    image: nginxinc/nginx-unprivileged
    ports:
    - containerPort: 8000
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -f /homework/index.html"]
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
    volumeMounts:
    - name: web-volume
      mountPath: /homework
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d
      readOnly: true
  initContainers:
  - name: init
    image: busybox:latest
    command: ['sh', '-c', 'mkdir /init; date > /init/index.html']
    volumeMounts:
    - name: web-volume
      mountPath: /init
  volumes:
  - name: web-volume
    emptyDir: {}
  - name: nginx-conf
    configMap:
      name: nginx-conf
      items:
        - key: nginx.conf
          path: nginx.conf
  terminationGracePeriodSeconds: 0
  securityContext:
    runAsUser: 1000
  dnsPolicy: Default
  nodeSelector:
    kubernetes.io/os: linux